### ISSUE TITLE
Allow to export interfaces on multiple paths

### ISSUE THREAD

**Issue by mdellweg** [acrisci/python-dbus-next#4]
Trying to export an interface the second time raises an error. However this seems to be necessary to implement the aliases described in:
https://standards.freedesktop.org/secret-service/ch04.html

**Comment by acrisci** [comment]
There are some edge cases with that I didn't feel like dealing with at the time, but there's no reason I can't support this with a bit of extra work.

Do you need to have request details in your handler like what object path it was called from?

**Comment by mdellweg** [comment]
That would be great. In my usecase it is really just like you can also access those objects by well known aliases. So they should not need to know, which path was used.

**Comment by mdellweg** [comment]
Wow, that was fast. Thank you! I will have a go with this.
