### ISSUE TITLE
Failed to activate service

### ISSUE THREAD

**Issue by Kavan72** [acrisci/python-dbus-next#6]
```Failed to activate service 'org.mpris.MediaPlayer2.vlc': timed out service_start_timeout=120000ms)```
anyway to control this timeout with dbus_next or can you implement this ?

**Comment by acrisci** [comment]
You can control this timeout in your dbus daemon [configuration file](https://dbus.freedesktop.org/doc/dbus-daemon.1.html) with a `<limit>` directive.

There's also a [NO_AUTOSTART](https://github.com/acrisci/python-dbus-next/blob/a952c825f6edd7dc34ccddd49cd485c2ebd22cd8/dbus_next/constants.py#L25) flag that can be used with a message to disable the autostart behavior.

> The bus must not launch an owner for the destination name in reasponse to this message.

**Comment by Kavan72** [comment]
i know this but i think this is weird way to do this, it's nice if you can implement this like call block or set `timeout`

**Comment by acrisci** [comment]
I could implement a timeout on dbus calls by throwing an exception for the call after a timer expires.

**Comment by Kavan72** [comment]
then it's nice. please implement timeout support fast

**Comment by Kavan72** [comment]
@acrisci sir, when you implement timeout ?

**Comment by acrisci** [comment]
How do you want to pass the timeout?

**Comment by Kavan72** [comment]
yes

**Comment by Kavan72** [comment]
like this 
```py
introspection = await bus.introspect('org.mpris.MediaPlayer2.vlc', '/org/mpris/MediaPlayer2', timeout=20)
```

**Comment by Kavan72** [comment]
@acrisci are you here ?

**Comment by acrisci** [comment]
I can implement this because I want you to use my library, but I personally don't need it so it might be awhile before this becomes a priority for me.

If you want it, go implement it. The source is right there. It's an easy fix. And you can have it just how you want it.

**Comment by Kavan72** [comment]
done and thx for your time
